const SCRABBLE_WORDS: { [length: number]: string[] } = {
  2: [
    'AA',
    'AB',
    'AD',
    'AE',
    'AG',
    'AH',
    'AI',
    'AL',
    'AM',
    'AN',
    'AR',
    'AS',
    'AT',
    'AW',
    'AX',
    'AY',
    'BA',
    'BE',
    'BI',
    'BO',
    'BY',
    'CH',
    'DA',
    'DE',
    'DI',
    'DO',
    'EA',
    'ED',
    'EE',
    'EF',
    'EH',
    'EL',
    'EM',
    'EN',
    'ER',
    'ES',
    'ET',
    'EW',
    'EX',
    'FA',
    'FE',
    'FY',
    'GI',
    'GO',
    'GU',
    'HA',
    'HE',
    'HI',
    'HM',
    'HO',
    'ID',
    'IF',
    'IN',
    'IO',
    'IS',
    'IT',
    'JA',
    'JO',
    'KA',
    'KI',
    'KO',
    'KY',
    'LA',
    'LI',
    'LO',
    'MA',
    'ME',
    'MI',
    'MM',
    'MO',
    'MU',
    'MY',
    'NA',
    'NE',
    'NO',
    'NU',
    'NY',
    'OB',
    'OD',
    'OE',
    'OF',
    'OH',
    'OI',
    'OK',
    'OM',
    'ON',
    'OO',
    'OP',
    'OR',
    'OS',
    'OU',
    'OW',
    'OX',
    'OY',
    'PA',
    'PE',
    'PI',
    'PO',
    'QI',
    'RE',
    'SH',
    'SI',
    'SO',
    'ST',
    'TA',
    'TE',
    'TI',
    'TO',
    'UG',
    'UH',
    'UM',
    'UN',
    'UP',
    'UR',
    'US',
    'UT',
    'WE',
    'WO',
    'XI',
    'XU',
    'YA',
    'YE',
    'YO',
    'YU',
    'ZA',
    'ZE',
    'ZO',
  ],
};

export const constants = {
  MSG_INVALID_COMMAND: 'Invalid command!',
  MSG_MISSING_COMMAND: 'Missing command!',
  MSG_MISSING_LENGTH: 'Missing word length to start a game!',
  MSG_INVALID_LENGTH: 'Invalid wordlength! Length must be a positive number!',
  MSG_NOT_IMPLEMENTED:
    'Words of that length is not implemented yet! Please try words of length 2.',
  MSG_INVALID_GUESS: 'Invalid guess! Please guess YES or NO.',
  MSG_GAME_STOPPED: 'Game stopped!',
  MSG_GAME_NOT_IN_PROGRESS: 'Game is not in progress!',

  HELP_START:
    "SCRABBLE START [NUMBER]: Stats a word scrabble guessing game by generating a potential word of length N for you to guess if it's a valid Scrabble word. For example, type SCRABBLE START 2 to start guessing potential 2 letter words.",
  HELP_GUESS:
    'SCRABBLE GUESS [YES/NO]: Guess whether the given word is valid. For example, type SCRABBLE GUESS YES if you think the given word is a valid Scrabble word.',
  HELP_STOP: 'SCRABBLE STOP: Stops the current game.',

  SCRABBLE_WORDS: SCRABBLE_WORDS,
};
