name: code-cov-workflow
run-name: ${{ github.actor }} is generating code-cov reports
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests with coverage
        run: npm run test:cov
